### ISSUE TITLE
Setting up project

### ISSUE THREAD

**Issue by jrcoimbra** [oli77za/zexp#1]
Hi, 

I just watched the Youtube video about this project and I would like to know how to set it up properly on my local machine. 
I installed the Meteor 1.2.1 version but I'm receiving the following error: 

W20160608-18:05:46.213(-3)? (STDERR)  
W20160608-18:05:46.214(-3)? (STDERR) /Users/../.meteor/packages/meteor-tool/.1.1.10.105f792++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160608-18:05:46.214(-3)? (STDERR)                        throw(ex);
W20160608-18:05:46.214(-3)? (STDERR)                              ^
W20160608-18:05:46.221(-3)? (STDERR) ReferenceError: Router is not defined
W20160608-18:05:46.222(-3)? (STDERR)     at server/Router.js:2:1
W20160608-18:05:46.222(-3)? (STDERR)     at /Users/.../zexp2/.meteor/local/build/programs/server/app/server/Router.js:22:4
W20160608-18:05:46.222(-3)? (STDERR)     at /Users/.../zexp2/.meteor/local/build/programs/server/boot.js:242:10
W20160608-18:05:46.222(-3)? (STDERR)     at Array.forEach (native)
W20160608-18:05:46.222(-3)? (STDERR)     at Function._.each._.forEach (/Users/.../.meteor/packages/meteor-tool/.1.1.10.105f792++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160608-18:05:46.222(-3)? (STDERR)     at /Users/.../zexp2/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8

Can you please provide the correct settings?

**Comment by oli77za** [comment]
This is quite strange, I can simply clone my project and run it.

The Router symbol is referring to iron:router

Can you confirm what version of node you are running?

**Comment by jrcoimbra** [comment]
Meteor: 1.3.4.1
Node: 4.2.6

**Comment by oli77za** [comment]
Node should be 0.10 or 0.12

You can use https://www.npmjs.com/package/nvm to switch the version.

Let me know if that works
